version: "3.7"

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: xhuma
      MYSQL_USER: abc
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"

  php:
    build: ./docker/php
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    command:
      - /bin/sh
      - -c
      - |
        echo "security.limit_extensions = .php .phtml .php3 .php4 .php5 .html .htm" >> /usr/local/etc/php-fpm.d/www.conf
        php-fpm

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "443:443"